- name: Sample Playbook
  hosts: all
  gather_facts: no

  tasks:
    - name: Ping localhost
      ping:

    - name: Create directory
      file:
        path: /app/ansible-test
        state: directory
        mode: '0755'

    - name: Create or update hello.txt with timestamp
      copy:
        dest: /app/ansible-test/hello.txt
        content: "Hello World - Updated at {{ lookup('pipe', 'date') }}"

    - name: Read hello.txt
      command: cat /app/ansible-test/hello.txt
      register: file_content

    - name: Show hello.txt
      debug:
        msg: "{{ file_content.stdout }}"